# Copyright (c) 2022, Antmicro
# SPDX-License-Identifier: Apache-2.0

name: Tests

on:
  push:
  pull_request:

jobs:
  test-tl-ahb-bridge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -qy install --no-install-recommends \
            python3-dev python3-pip git gperf autoconf flex bison build-essential perl \
            libfl-dev libfl2 zlib1g zlib1g-dev

      - name: Build Verilator
        run: |
          git clone -b Fix_VPI_interface https://github.com/antmicro/verilator-1.git verilator
          cd verilator
          autoconf
          ./configure && make -j$(nproc) && sudo make install
          cd ..

      - name: Install python dependencies
        run: |
          python3 -m pip install cocotb-AHB cocotb-TileLink

      - name: Test
        run: |
          ls
          make test | tee log.txt
      - name: Check results
        run: |
          ! cat $(find . -name "results.xml") | grep -cq "<failure />"
